#!/usr/bin/bash
#
# When I new to bunsenlibs.
#
# 第一次使用bunsenlibs, 趟了好几次，
# 所以记录笔记，以防不测 = =!!
#

# 添加vpn管理器
sudo apt-get install pptpd network-manager-pptp-gnome

# 添加nvidia显卡驱动
# 首先要把nouveau填进黑名单
echo "blacklist nouveau" >> /etc/modprobe.d/nvidia-blacklists-nouveau.conf
sudo apt-get install nvidia-driver nvidia-xconfig
sudo nvidia-xconfig
# 重启lightmd
sudo service lightmd reload
# 修改xorg配置
sudo rm /etc/X11/xorg.conf
sudo echo "\
# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 340.46  (buildd@brahms)  Tue Oct  7 08:00:32 UTC 2014


Section \"ServerLayout\"
    Identifier     \"Layout0\"
    Screen      0  \"Screen0\" 0 0
    InputDevice    \"Keyboard0\" \"CoreKeyboard\"
    InputDevice    \"Mouse0\" \"CorePointer\"
EndSection

Section \"Files\"
EndSection

Section \"InputDevice\"

    # generated from default
    Identifier     \"Mouse0\"
    Driver         \"mouse\"
    Option         \"Protocol\" \"auto\"
    Option         \"Device\" \"/dev/psaux\"
    Option         \"Emulate3Buttons\" \"no\"
    Option         \"ZAxisMapping\" \"4 5\"
EndSection

Section \"InputDevice\"

    # generated from default
    Identifier     \"Keyboard0\"
    Driver         \"kbd\"
EndSection

Section \"Monitor\"
    Identifier     \"Monitor0\"
    VendorName     \"Unknown\"
    ModelName      \"DDL MW19H\"
    HorizSync       30.0 - 80.0
    VertRefresh     55.0 - 75.0
    #Option         \"DPMS\"
EndSection

Section \"Device\"
    Identifier     \"Device0\"
    Driver         \"nvidia\"
    VendorName     \"NVIDIA Corporation\"
EndSection

Section \"Screen\"
    Identifier     \"Screen0\"
    Device         \"Device0\"
    Monitor        \"Monitor0\"
    Option	   \"metamodes\" \"CRT:1360x768 0 0;CRT:1360x768_60 0 0;CRT:nvidia-auto-seect 0\"
    DefaultDepth    24
    SubSection     \"Display\"
        Depth       24
    EndSubSection
EndSection
" >> /etc/X11/xorg.conf

# 配置fcitx输入法
sudo apt-get install fcitx fcitx-pinyin
im-config
sudo service lightmd reload

# 下载emacs
sudo apt-get install emacs

# ok, 基本能正常工作了
