#!/usr/bin/bash
#
# When I new to bunsenlibs.
#
# 第一次使用bunsenlibs, 趟了好几次，
# 所以记录笔记，以防不测 = =!!
#

# 添加vpn管理器
sudo apt-get install pptpd network-manager-pptp-gnome

# 添加nvidia显卡驱动
# 首先要把nouveau填进黑名单
echo "blacklist nouveau" >> /etc/modprobe.d/nvidia-blacklists-nouveau.conf
sudo apt-get install nvidia-driver nvidia-xconfig
sudo nvidia-xconfig
# 重启lightmd
sudo service lightmd reload
# 修改xorg配置
sudo rm /etc/X11/xorg.conf
sudo echo "\
# nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 340.46  (pbuilder@zam904)  Fri Oct 17 21:29:34 UTC 2014

# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 340.46  (buildd@brahms)  Tue Oct  7 08:00:32 UTC 2014

Section \"ServerLayout\"
    Identifier     \"Layout0\"
    Screen      0  \"Screen0\" 0 0
    InputDevice    \"Keyboard0\" \"CoreKeyboard\"
    InputDevice    \"Mouse0\" \"CorePointer\"
    Option         \"Xinerama\" \"0\"
EndSection

Section \"Files \"
EndSection

Section  \"InputDevice \"

    # generated from default
    Identifier      \"Mouse0 \"
    Driver          \"mouse \"
    Option          \"Protocol \"  \"auto \"
    Option          \"Device \"  \"/dev/psaux \"
    Option          \"Emulate3Buttons \"  \"no \"
    Option          \"ZAxisMapping \"  \"4 5 \"
EndSection

Section  \"InputDevice \"

    # generated from default
    Identifier      \"Keyboard0 \"
    Driver          \"kbd \"
EndSection

Section  \"Monitor \"

    #Option         \"DPMS\"
    Identifier     \"Monitor0\"
    VendorName     \"Unknown\"
    ModelName      \"CRT-0\"
    HorizSync       30.0 - 80.0
    VertRefresh     55.0 - 75.0
EndSection

Section \"Device\"
    Identifier     \"Device0\"
    Driver         \"nvidia\"
    VendorName     \"NVIDIA Corporation\"
    BoardName      \"GeForce GTX 650\"
EndSection

Section \"Screen\"

# Removed Option \"metamodes\" \"CRT:1360x768 0 0;CRT:1360x768_60 0 0;CRT:nvidia-auto-seect 0\"
# Removed Option \"metamodes\" \"1360x768 +0+0\"
    Identifier     \"Screen0\"
    Device         \"Device0\"
    Monitor        \"Monitor0\"
    DefaultDepth    24
    Option         \"Stereo\" \"0\"
    Option         \"nvidiaXineramaInfoOrder\" \"CRT-0\"
    Option         \"metamodes\" \"nvidia-auto-select +0+0\"
    Option         \"SLI\" \"Off\"
    Option         \"MultiGPU\" \"Off\"
    Option         \"BaseMosaic\" \"off\"
    SubSection     \"Display\"
        Depth       24
    EndSubSection
EndSection

" >> /etc/X11/xorg.conf

# 配置fcitx输入法
sudo apt-get install fcitx fcitx-pinyin
im-config
sudo service lightmd reload



# ok, 基本能正常工作了
# 下面添加编程工具

# 下载emacs
sudo apt-get install emacs

# clojure
# leiningen 需要爬墙
java -version
sudo curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o /usr/local/bin/lein
sudo chmod 775 /usr/local/bin/lein
cd /usr/local/bin/
./lein

# haskell
sudo apt-get install haskell-platform
